language: node_js

node_js:
  - "8.9"
  - "12"

# env:
#   - CONTEXT=XXX

# before_install:
#   - stty columns 120

install:
  - npm install

script:
  - TRAVIS=true npm run test:debug

# sudo: false

# notifications:
#   email: false
